workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60  # Max build duration in minutes
    environment:
      node: latest  # Specify the latest Node.js version or a specific version if needed
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @ionic/cli
          npm install -g @capacitor/cli
      - name: Build the app
        script: |
          ionic build
          ionic capacitor sync ios
      - name: Create iOS build
        script: |
          cd ios/App
          xcodebuild -scheme App -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/App.xcarchive
    artifacts:
      - ios/App.xcarchive  # Archive file to keep
      - ios/App.ipa        # Specify the generated .ipa file location
    publishing:
      scripts:
        - name: Publish to App Store (Optional)
          script: |
            # Commands to publish the .ipa to App Store Connect or another service
