workflows:
  ios-build:
    name: iOS Build
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install -g @ionic/cli
          npm install
      - name: Build the app
        script: |
          ionic build
          ionic capacitor build ios --prod
      - name: Sync with iOS
        script: |
          capacitor sync ios
    artifacts:
      - ios/App/App/build/ios/ipa/*.ipa # Adjust this path if needed based on where the IPA file is generated
