workflows:
  ios-build:
    name: iOS Build
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install Ionic CLI and Capacitor
        script: |
          npm install -g @ionic/cli
          npm install -g @capacitor/cli # Install Capacitor CLI globally
          npm install
      - name: Build the app
        script: |
          ionic build
          ionic capacitor build ios --prod
      - name: Sync with iOS
        script: |
          npx cap sync ios # Use npx to run Capacitor without global installation issues
    artifacts:
      - ios/App/App/build/ios/ipa/*.ipa # Adjust this path if needed based on where the IPA file is generated
